# Generated by Django 2.1 on 2018-10-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=64, null=True)),
                ('authority', models.IntegerField()),
                ('description', models.TextField()),
                ('fromCurrencyCode', models.IntegerField()),
                ('toCurrencyCode', models.IntegerField()),
                ('firstName', models.CharField(max_length=225)),
                ('lastName', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('mobile', models.CharField(max_length=225)),
                ('orderNumber', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=225)),
                ('postalCode', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
