# Generated by Django 2.0.9 on 2018-10-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yekpay', '0002_auto_20181023_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fromCurrencyCode',
            field=models.CharField(choices=[('EUR', 'Euro'), ('IRR', 'Iranian Rial'), ('CHF', 'Swiss Franc'), ('AED', 'United Arab Emirates Dirham'), ('CNY', 'Chinese Yuan'), ('GBP', 'British Pound'), ('JPY', 'Japanese 100 Yens'), ('RUB', 'Russian Ruble'), ('TRY', 'Turkish New Lira')], default='EUR', max_length=4),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='toCurrencyCode',
            field=models.CharField(choices=[('EUR', 'Euro'), ('IRR', 'Iranian Rial'), ('CHF', 'Swiss Franc'), ('AED', 'United Arab Emirates Dirham'), ('CNY', 'Chinese Yuan'), ('GBP', 'British Pound'), ('JPY', 'Japanese 100 Yens'), ('RUB', 'Russian Ruble'), ('TRY', 'Turkish New Lira')], default='EUR', max_length=4),
        ),
    ]
