# Generated by Django 2.0.9 on 2018-10-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yekpay', '0004_auto_20181023_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='failureReason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
