# Generated by Django 2.0.9 on 2018-10-23 14:29

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('yekpay', '0006_auto_20181023_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='orderNumber',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', blank=True, min_length=7, null=True),
        ),
    ]
