# Generated by Django 2.0.9 on 2018-10-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yekpay', '0011_auto_20181025_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='redirect_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Transaction has just started'), ('INCOMPLETE_PARAMETERS', 'Transaction parameters were incomplete'), ('MERCHANT_CODE_INCORRECT', 'Merchant code was incorrect'), ('MERCHANT_CODE_NOT_ACTIVE', 'Merchant code is not active'), ('AUTHORITY_CODE_INVALID', 'Authority code was invalid'), ('ALREADY_VERIFIED', 'Transaction was already verified'), ('FAILED', 'Transaction was failed'), ('UNKNOWN', 'Transaction was failed with unknown error'), ('SUCCESS', 'Transaction was successfully done')], max_length=100),
        ),
    ]
