# Generated by Django 2.0.9 on 2018-10-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yekpay', '0003_auto_20181023_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Transaction has just started'), ('INCOMPLETE_PARAMETERS', 'Transaction parameters were incomplete'), ('MERCHANT_CODE_INCORRECT', 'Merchant code was incorrect'), ('MERCHANT_CODE_NOT_ACTIVE', 'Merchant code is not active'), ('AUTHORITY_CODE_INVALID', 'Authority code was invalid'), ('ALREADY_VERIFIED', 'Transaction was already verfied'), ('FAILDED', 'Transaction was failed'), ('UNKNOWN', 'Transaction was failed with unknown error'), ('SUCCESS', 'Transaction was successfully done')], max_length=100),
        ),
    ]
