# Generated by Django 2.0.9 on 2018-10-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yekpay', '0005_transaction_failurereason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='authority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
