# Generated by Django 2.0.9 on 2018-10-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yekpay', '0008_auto_20181023_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='authority',
            new_name='authorityStart',
        ),
        migrations.AddField(
            model_name='transaction',
            name='authorityVerify',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
