# Generated by Django 2.0.9 on 2018-10-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yekpay', '0009_auto_20181023_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='authorityStart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='authorityVerify',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
