# Generated by Django 2.0.9 on 2018-10-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yekpay', '0012_auto_20181029_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='redirect_url',
            new_name='callback_url',
        ),
    ]
