# Generated by Django 2.0.9 on 2018-11-20 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yekpay', '0013_auto_20181030_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='authorityStart',
            new_name='authority_start',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='authorityVerify',
            new_name='authority_verify',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='failureReason',
            new_name='failure_reason',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='fromCurrencyCode',
            new_name='from_currency_code',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='orderNumber',
            new_name='order_number',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='postalCode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='toCurrencyCode',
            new_name='to_currency_code',
        ),
        migrations.AddField(
            model_name='transaction',
            name='simulation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
