# Generated by Django 2.0.9 on 2018-12-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yekpay', '0015_transaction_successfull_payment_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='successfull_payment_date_time',
            new_name='successful_payment_date_time',
        ),
    ]
