# Generated by Django 2.0.9 on 2019-03-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yekpay', '0016_auto_20181206_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
