# Generated by Django 2.0.9 on 2019-10-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yekpay', '0018_auto_20190721_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='failure_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
