# Generated by Django 2.0.9 on 2019-11-28 12:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yekpay', '0019_transaction_failure_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='additional_callback_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, max_length=1000, null=True),
        ),
    ]
